Add python version check
1) download & install async-periodic
2) put readme sample into file
3) run it
4) get "AttributeError: module 'asyncio' has no attribute 'create_task'"
5) google it
6) found out that periodic requires Python 3.7 but you have 3.6
7) write PR so periodic could say about requirements by itself